baseURL: http://lynn404.com/
languageCode: zh-cn
title: Lynn的技术随笔
theme: LoveIt
languageName: 简体中文
hasCJKLanguage: true
author:
  name: Lynn
menu:
  main:
    - weight: 1
      identifier: "posts"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre: ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post: ""
      name: "文章"
      url: "/posts/"
      # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
      title: ""
    - weight: 2
      identifier: "tags"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre: ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post: ""
      name: "标签"
      url: "/tags/"
      # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
      title: ""
    - weight: 3
      identifier: "categories"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre: ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post: ""
      name: "分类"
      url: "/categories/"
      # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
      title: ""
markup:
  highlight:
    noClasses: false